#############################################################################
# Makefile for building: Psion5mxEmulator
# Generated by qmake (3.1) (Qt 6.2.0)
# Project:  Psion5mxEmulator.pro
# Template: subdirs
# Command: C:\Qt\6.2.0\mingw81_64\bin\qmake.exe -o Makefile Psion5mxEmulator.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\6.2.0\mingw81_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\6.2.0\mingw81_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\6.2.0\mingw81_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = cmd /c move
TAR           = 
COMPRESS      = 
DISTNAME      = Psion5mxEmulator1.0.0
DISTDIR = D:\PSION\Psion5mxEmulator\.tmp\Psion5mxEmulator1.0.0
SUBTARGETS    =  \
		sub-Psion5mxEmulatorCore \
		sub-Psion5mxEmulatorQt


sub-Psion5mxEmulatorCore-qmake_all:  FORCE
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler"
	cd Psion5mxEmulatorCore\ && $(MAKE) -f Makefile qmake_all
sub-Psion5mxEmulatorCore: FORCE
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Psion5mxEmulatorCore-make_first: FORCE
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Psion5mxEmulatorCore-all: FORCE
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Psion5mxEmulatorCore-clean: FORCE
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Psion5mxEmulatorCore-distclean: FORCE
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Psion5mxEmulatorCore-install_subtargets: FORCE
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Psion5mxEmulatorCore-uninstall_subtargets: FORCE
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Psion5mxEmulatorQt-qmake_all:  FORCE
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler"
	cd Psion5mxEmulatorQt\ && $(MAKE) -f Makefile qmake_all
sub-Psion5mxEmulatorQt: FORCE
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Psion5mxEmulatorQt-make_first: FORCE
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Psion5mxEmulatorQt-all: FORCE
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Psion5mxEmulatorQt-clean: FORCE
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Psion5mxEmulatorQt-distclean: FORCE
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Psion5mxEmulatorQt-install_subtargets: FORCE
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Psion5mxEmulatorQt-uninstall_subtargets: FORCE
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall

Makefile: Psion5mxEmulator.pro C:\Qt\6.2.0\android_arm64_v8a\mkspecs\android-clang\qmake.conf C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\spec_pre.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\unix.conf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\linux.conf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\sanitize.conf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\gcc-base.conf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\gcc-base-unix.conf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\clang.conf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\qdevice.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\device_config.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\qconfig.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_ext_freetype.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_ext_libpng.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_bodymovin_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_chartsqml.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_chartsqml_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_core5compat.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_core5compat_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_datavisualization.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_datavisualization_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_input_support_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsanimation.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsanimation_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labssettings.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labssettings_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labssharedimage.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_linguist.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_linguist_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_multimediaquick_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_networkauth.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_networkauth_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_openglwidgets.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_positioningquick.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_positioningquick_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlcore.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlcore_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmldom_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlmodels.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3d.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3d_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetutils.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetutils_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3deffects.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3deffects_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dhelpers.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dhelpers_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3diblbaker.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3diblbaker_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dparticles.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dparticles_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dutils.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicklayouts.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickshapes_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicktemplates2.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicktimeline.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicktimeline_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_remoteobjectsqml.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_repparser.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_scxmlqml.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_scxmlqml_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sensorsquick.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sensorsquick_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_shadertools.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_shadertools_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_statemachine.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_statemachine_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_statemachineqml.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_statemachineqml_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_svgwidgets.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_tools_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webviewquick.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webviewquick_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\qt_functions.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\qt_config.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\android-clang\qmake.conf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\spec_post.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\android\spec_post.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\exclusive_builds.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\toolchain.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\default_pre.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\android\default_pre.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\resolve_config.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\android\resolve_config.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\default_post.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\qtquickcompiler.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\android\android.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\android\android_deployment_settings.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\warn_on.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\qmake_use.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\file_copies.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\testcase_targets.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\exceptions.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\yacc.prf \
		C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\lex.prf \
		Psion5mxEmulator.pro
	$(QMAKE) -o Makefile Psion5mxEmulator.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler"
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\spec_pre.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\unix.conf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\linux.conf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\sanitize.conf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\gcc-base.conf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\gcc-base-unix.conf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\common\clang.conf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\qdevice.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\device_config.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\qconfig.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_ext_freetype.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_ext_libpng.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_bodymovin_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_chartsqml.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_chartsqml_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_core.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_core5compat.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_core5compat_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_datavisualization.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_datavisualization_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_help.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_input_support_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsanimation.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsanimation_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsqmlmodels.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labssettings.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labssettings_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labssharedimage.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labssharedimage_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_linguist.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_linguist_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_multimediaquick_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_network.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_networkauth.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_networkauth_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_openglwidgets.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_openglwidgets_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_positioningquick.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_positioningquick_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlcore.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlcore_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmldom_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmllocalstorage.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlmodels.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlmodels_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlworkerscript.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3d.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3d_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetimport.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetutils.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetutils_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3deffects.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3deffects_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dhelpers.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dhelpers_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3diblbaker.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3diblbaker_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dparticles.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dparticles_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3druntimerender.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dutils.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dutils_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicklayouts.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicklayouts_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickshapes_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicktemplates2.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicktimeline.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quicktimeline_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_remoteobjectsqml.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_repparser.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_repparser_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_scxmlqml.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_scxmlqml_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sensorsquick.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sensorsquick_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_shadertools.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_shadertools_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_statemachine.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_statemachine_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_statemachineqml.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_statemachineqml_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_svgwidgets.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_svgwidgets_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_tools_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_virtualkeyboard.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webviewquick.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_webviewquick_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\qt_functions.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\qt_config.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\android-clang\qmake.conf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\spec_post.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\android\spec_post.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\exclusive_builds.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\toolchain.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\default_pre.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\android\default_pre.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\resolve_config.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\android\resolve_config.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\default_post.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\qtquickcompiler.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\android\android.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\android\android_deployment_settings.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\warn_on.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\qmake_use.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\file_copies.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\testcase_targets.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\exceptions.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\yacc.prf:
C:\Qt\6.2.0\android_arm64_v8a\mkspecs\features\lex.prf:
Psion5mxEmulator.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Psion5mxEmulator.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler"

qmake_all: sub-Psion5mxEmulatorCore-qmake_all sub-Psion5mxEmulatorQt-qmake_all FORCE

make_first: sub-Psion5mxEmulatorCore-make_first sub-Psion5mxEmulatorQt-make_first  FORCE
all: sub-Psion5mxEmulatorCore-all sub-Psion5mxEmulatorQt-all  FORCE
clean: sub-Psion5mxEmulatorCore-clean sub-Psion5mxEmulatorQt-clean  FORCE
distclean: sub-Psion5mxEmulatorCore-distclean sub-Psion5mxEmulatorQt-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-Psion5mxEmulatorCore-install_subtargets sub-Psion5mxEmulatorQt-install_subtargets FORCE
uninstall_subtargets: sub-Psion5mxEmulatorCore-uninstall_subtargets sub-Psion5mxEmulatorQt-uninstall_subtargets FORCE

sub-Psion5mxEmulatorCore-aab:
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile aab
sub-Psion5mxEmulatorQt-aab:
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile aab
aab: sub-Psion5mxEmulatorCore-aab sub-Psion5mxEmulatorQt-aab

sub-Psion5mxEmulatorCore-apk:
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile apk
sub-Psion5mxEmulatorQt-apk:
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile apk
apk: sub-Psion5mxEmulatorCore-apk sub-Psion5mxEmulatorQt-apk

sub-Psion5mxEmulatorCore-apk_install_target:
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile apk_install_target
sub-Psion5mxEmulatorQt-apk_install_target:
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile apk_install_target
apk_install_target: sub-Psion5mxEmulatorCore-apk_install_target sub-Psion5mxEmulatorQt-apk_install_target

sub-Psion5mxEmulatorCore-check:
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-Psion5mxEmulatorQt-check:
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
check: sub-Psion5mxEmulatorCore-check sub-Psion5mxEmulatorQt-check

sub-Psion5mxEmulatorCore-benchmark:
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-Psion5mxEmulatorQt-benchmark:
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-Psion5mxEmulatorCore-benchmark sub-Psion5mxEmulatorQt-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-Psion5mxEmulatorCore-distdir sub-Psion5mxEmulatorQt-distdir FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents  $(DISTDIR)\

sub-Psion5mxEmulatorCore-distdir: FORCE
	@if not exist Psion5mxEmulatorCore\ mkdir Psion5mxEmulatorCore\ & if not exist Psion5mxEmulatorCore\ exit 1
	cd Psion5mxEmulatorCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorCore\Psion5mxEmulatorCore.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)\Psion5mxEmulatorCore

sub-Psion5mxEmulatorQt-distdir: FORCE
	@if not exist Psion5mxEmulatorQt\ mkdir Psion5mxEmulatorQt\ & if not exist Psion5mxEmulatorQt\ exit 1
	cd Psion5mxEmulatorQt\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\PSION\Psion5mxEmulator\Psion5mxEmulatorQt\Psion5mxEmulatorQt.pro -qtconf C:/Qt/6.2.0/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=qtquickcompiler" ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)\Psion5mxEmulatorQt

